
/**
 * ESTA PROHIBIDO EL USO DE SIMULACION Y MANIPULACION DE DATOS, APLICACION DE USO REFERENCIAL MEDICA
 */

export const DETECTION_CONFIG = {
  HISTORY_SIZE: 5,
  ADAPTIVE_ADJUSTMENT_INTERVAL: 40,
  MIN_DETECTION_THRESHOLD: 0.30,
  MAX_SIGNAL_LOCK: 4,
  RELEASE_GRACE_PERIOD: 3
};
